# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getH_ik_RCPP <- function(x, i, k, p, Phi, eps) {
    .Call(`_mosumvar_H_ik`, x, i, k, p, Phi, eps)
}

getH_ik_univ <- function(z, x, i, k, p, Phi, eps) {
    .Call(`_mosumvar_H_ik_univ`, z, x, i, k, p, Phi, eps)
}

makeH_k_RCPP <- function(x, k, p, Phi, eps) {
    .Call(`_mosumvar_H_k`, x, k, p, Phi, eps)
}

makeH_k_univ <- function(z, x, k, p, PhiList, eps) {
    .Call(`_mosumvar_H_k_univ`, z, x, k, p, PhiList, eps)
}

makeH_all_RCPP <- function(x, p, G, Phi, eps) {
    .Call(`_mosumvar_H_all`, x, p, G, Phi, eps)
}

makeH_all_univ <- function(z, x, p, G, PhiList, eps) {
    .Call(`_mosumvar_H_all_univ`, z, x, p, G, PhiList, eps)
}

get_DiagH_RCPP <- function(x, k, G, p, h_all) {
    .Call(`_mosumvar_DiagH`, x, k, G, p, h_all)
}

get_FullH_RCPP <- function(x, k, G, h_all) {
    .Call(`_mosumvar_FullH`, x, k, G, h_all)
}

getA_RCPP <- function(x, k, G, p, h_all) {
    .Call(`_mosumvar_getA`, x, k, G, p, h_all)
}

getsigma_iGlobal_RCPP <- function(eps, p, i) {
    .Call(`_mosumvar_getsigma_iGlobal`, eps, p, i)
}

getsigma_dGlobal_RCPP <- function(eps, p) {
    .Call(`_mosumvar_getsigma_dGlobal`, eps, p)
}

getsigma_dLocal_RCPP <- function(eps, k, p, G) {
    .Call(`_mosumvar_getsigma_dLocal`, eps, k, p, G)
}

get_DiagC_RCPP <- function(x, p, sigma_d, k, G, root = FALSE) {
    .Call(`_mosumvar_DiagC`, x, p, sigma_d, k, G, root)
}

get_DiagC_univ <- function(x, p, sigma_d, k, G, root = FALSE) {
    .Call(`_mosumvar_DiagC_univ`, x, p, sigma_d, k, G, root)
}

get_Tkn_RCPP <- function(x, k, p, G, Phi, eps, h_all, estim, var_estim, sgd, univariate = 0L) {
    .Call(`_mosumvar_Tkn`, x, k, p, G, Phi, eps, h_all, estim, var_estim, sgd, univariate)
}

get_T_RCPP <- function(x, p, G, Phi, eps, PhiList, estim = "C", var_estim = "Local", univariate = 0L, R = 1L) {
    .Call(`_mosumvar_T`, x, p, G, Phi, eps, PhiList, estim, var_estim, univariate, R)
}

get_T_univ <- function(z, x, p, G, Phi, eps, PhiList, estim = "C", var_estim = "Local") {
    .Call(`_mosumvar_T_univ`, z, x, p, G, Phi, eps, PhiList, estim, var_estim)
}

test_Score_RCPP <- function(x, p, G, Phi, eps, alpha = 0.05, estim = "C") {
    .Call(`_mosumvar_test_Score`, x, p, G, Phi, eps, alpha, estim)
}

MFA_Score <- function(x, p, Gset, Phi, eps, estim = "C", alpha = 0.05, nu = 0.25) {
    .Call(`_mosumvar_MFA_Score`, x, p, Gset, Phi, eps, estim, alpha, nu)
}

VAR_sim <- function(n, mu, Sigma, coeffs, error_dist, P1, Q1, df = 3L) {
    .Call(`_mosumvar_VAR_sim`, n, mu, Sigma, coeffs, error_dist, P1, Q1, df)
}

getH_ik_Wald_RCPP <- function(x, i, k, p, a) {
    .Call(`_mosumvar_H_ik_Wald`, x, i, k, p, a)
}

makeH_k_Wald_RCPP <- function(x, k, p, a) {
    .Call(`_mosumvar_H_k_Wald`, x, k, p, a)
}

makeH_l_u_RCPP <- function(x, p, l, u, a) {
    .Call(`_mosumvar_H_l_u`, x, p, l, u, a)
}

write_rows2 <- function(data, nrows, ncols) {
    .Call(`_mosumvar_write_rows2`, data, nrows, ncols)
}

get_a_lu_i_RCPP <- function(x, i, p, l, u) {
    .Call(`_mosumvar_a_lu_i`, x, i, p, l, u)
}

make_a_lu_RCPP <- function(x, p, l, u) {
    .Call(`_mosumvar_make_a_lu`, x, p, l, u)
}

get_V_nk_RCPP <- function(x, p, l, u) {
    .Call(`_mosumvar_V_nk`, x, p, l, u)
}

getsigma_i_kLOCAL1_RCPP <- function(x, i, k, G, p, a_upper) {
    .Call(`_mosumvar_sigma_i_k`, x, i, k, G, p, a_upper)
}

getsigma_d_kLOCAL1_RCPP <- function(x, k, G, p, a_upper, a_lower) {
    .Call(`_mosumvar_sigma_d_k`, x, k, G, p, a_upper, a_lower)
}

get_DiagH_Wald_RCPP <- function(x, G, p, H_l, H_u) {
    .Call(`_mosumvar_diagH_Wald`, x, G, p, H_l, H_u)
}

get_FullH_Wald_RCPP <- function(x, G, H_l, H_u) {
    .Call(`_mosumvar_FullH_Wald`, x, G, H_l, H_u)
}

get_DiagC_Wald_RCPP <- function(x, p, sigma_d, k, G) {
    .Call(`_mosumvar_DiagC_Wald`, x, p, sigma_d, k, G)
}

get_Wkn_RCPP <- function(x, p, k, G, estim = "C") {
    .Call(`_mosumvar_Wkn`, x, p, k, G, estim)
}

get_W_RCPP <- function(x, p, G, estim = "C") {
    .Call(`_mosumvar_W`, x, p, G, estim)
}

get_cps_RCPP <- function(Wn, D_n, G, nu = 0.25) {
    .Call(`_mosumvar_cps_Wald`, Wn, D_n, G, nu)
}

test_Wald_RCPP <- function(x, p, G, alpha = 0.05, estim = "C") {
    .Call(`_mosumvar_test_Wald`, x, p, G, alpha, estim)
}

sim_data_RCPP <- function(pars, n = 1000L, d = 5L, sd = 0.2) {
    .Call(`_mosumvar_sim_data`, pars, n, d, sd)
}

MFA_Wald <- function(x, p, Gset, estim = "C", alpha = 0.05, nu = 0.25) {
    .Call(`_mosumvar_MFA_Wald`, x, p, Gset, estim, alpha, nu)
}

